<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <title><?= $title ?></title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a class="nav-link" href="">The Peaky Blinders</a></li>
                    <li class="nav-item"><a class="nav-link" href="chapters">Capítulos</a></li>
                    <li class="nav-item"><a class="nav-link" href="season">Temporadas</a></li>
                </ul>

                <ul class="navbar-nav ms-auto">
                    <?php if (!empty($user->id)): ?>
                        <li class="nav-item">
                            <span class="nav-link text-dark"><?= htmlspecialchars($user->username) ?></span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="logout">Salir</a>
                        </li>
                    <?php else: ?>
                        <li class="nav-item">
                            <a class="nav-link text-primary" href="login">Ingresar</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>
</header>
<main class="container mt-3">
