<?php require 'layouts/header.phtml' ?>

<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-8">
                <div class="card-body mt-5">
                    <h2><?= $chapter->Titulo ?></h2>
                    <p><span>Titilo: </span><?= $chapter->Titulo ?></p>
                    <p><span>Descripcion: </span><?= $chapter->Descripcion ?></p>
                    <b><span>Personajes que participan: </span><?= $chapter->Personajes ?></b>
                    
                 
                </div>
            </div>
        </div>
    </div>
</div>

<?php require 'layouts/footer.phtml' ?>