<form action="new-chapter" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="Name" type="text" class="form-control">
            </div>
        </div>
    <div class="form-group">
        <label>Fecha Estreno</label>
        <textarea name="premiere_date" class="form-control" rows="3"></textarea>
    </div>
    <div class="form-group">
        <label>Productora</label>
        <textarea name="Producer" class="form-control" rows="3"></textarea>
    </div>
    <div class="form-group">
        <label>Imagen</label>
        <textarea name="image" class="form-control" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>