<?php require 'layouts/header.phtml' ?>

<div class="row">
    <?php if(!empty($user->id)): ?>
        <div class="col-md-4">
            <div class="card px-4">
                <?php require_once './templates/form.add.chapter.phtml' ?>
            </div>
        </div>
    <?php endif; ?>

    <div class="col-md-8">
        <ul class="list-group">
            <?php  foreach($seasons as $season) { ?>
                <li class="list-group-item item-task ">
                    <div class="label">
                        <b><?= htmlspecialchars($season->Nombre) ?> | <?= htmlspecialchars($season->Fecha_estreno) ?> | <?= htmlspecialchars($season->Productora) ?> | <img src=" <?= $season->imagen ?>" alt=""></b>
                    </div>
                    <div class="actions">
                        <a href="<?= BASE_URL . 'list-seasons' . $season->ID_serie ?>" type="button" class='btn btn-success btn-sm ml-auto'>Descripcion</a>
                    </div>
                    
                </li>
            <?php } ?>
        </ul>

        <p class="mt-3"><small>Mostrando <? $count?> Temporadas</small></p>
    </div>
</div>

<?php require 'layouts/footer.phtml' ?>
